version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: db
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/ht/Documents/code/js/mong/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: 'no'
